### ISSUE TITLE
Unable to publish when environments are not in the scope of export-import

### ISSUE THREAD

**Issue by kubamarszal** [contentstack/contentstack-import#37]
Hey guys,
My goal was to migrate one stack to the other. I've excluded environments and webhooks from export/import (as these differ from stack to stack in my case).

When I launched the import script everything has been migrated but none of the entries were published (./config/defaults.js - flag "entriesPublish" set to true).

The reason for that seems to be lib/import/entries.js:789:33 as I'm getting dozens of following errors:

`Unhandled rejection TypeError: Cannot read property 'hasOwnProperty' of undefined
    at /Users/jamarszal/src/contentstack/contentstack-import/lib/import/entries.js:789:33
    at arrayEach (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/lodash/lodash.js:9342:14)
    at /Users/jamarszal/src/contentstack/contentstack-import/lib/import/entries.js:788:11
    at Promise._execute (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/promise.js:79:10)
    at importEntries.publish (/Users/jamarszal/src/contentstack/contentstack-import/lib/import/entries.js:787:16)
    at /Users/jamarszal/src/contentstack/contentstack-import/lib/import/entries.js:461:42
    at tryCatcher (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jamarszal/src/contentstack/contentstack-import/node_modules/bluebird/js/release/async.js:143:10)`

**Comment by abhinav-from-contentstack** [comment]
Hi @kubamarszal, since the environments differ from stack to stack, publishing entries in the destination stack won't be possible. So, setting the `entriesPublish` flag to false will be appropriate in this case, because to publish entries, the data for the environment where they are supposed to be published is required.

**Comment by kubamarszal** [comment]
I do understand and agree 100% with you.
My main concern reporting this issue was the amount of errors I received in the terminal. Maybe it would be good to handle them somehow?

**Comment by kubamarszal** [comment]
Thank you so much! Appreciate.
